window.SANAGUSTIN_SEED = {
  categories: [
    { id: "cat-001", slug: "electronica", name: "Electrónica", description: "Auriculares, cargadores y gadgets prácticos." },
    { id: "cat-002", slug: "hogar", name: "Hogar", description: "Lámparas, accesorios y pequeños artículos para el hogar." },
    { id: "cat-003", slug: "juguetes", name: "Juguetes", description: "Figuras, juguetes creativos y llaveros divertidos." },
    { id: "cat-004", slug: "oficina", name: "Oficina", description: "Suministros básicos de oficina, bolígrafos y organizadores." }
  ],
  products: [
    {
      id: "prod-1001",
      slug: "audifonos-inalambricos-be-loud",
      name: "Auriculares Be Loud",
      category_id: "cat-001",
      description: "Auriculares inalámbricos con estuche de carga y sonido HiFi.",
      shortDescription: "Bluetooth, estuche 3500mAh y carga rápida.",
      price: 1299.00,
      currency: "ARS",
      stock: 16,
      sku: "ELECT_BLOUD_01",
      rating: 4.4,
      images: ["img/Inalámbricos Bluetooth Built In 5.3.webp"],
      tags: ["audio", "inalambrico", "carga", "gadget"],
      available: true
    },
    {
      id: "prod-1002",
      slug: "lampara-astronauta-led",
      name: "Lámpara Astronauta LED",
      category_id: "cat-002",
      description: "Lámpara de diseño con figura de astronauta para escritorio y ambiente.",
      shortDescription: "Luz suave, USB recargable y diseño kids-friendly.",
      price: 895.00,
      currency: "ARS",
      stock: 32,
      sku: "HOGAR_ASTR_02",
      rating: 4.7,
      images: ["img/Lampara Velador Recargable 29x12Cm Led Superior e Inferior Astronauta, Color Blanco.webp"],
      tags: ["iluminacion", "decoracion", "usb"],
      available: true
    },
    {
      id: "prod-1003",
      slug: "prueba-de-billetes-led",
      name: "Pluma Tester de Billetes",
      category_id: "cat-004",
      description: "Pluma detectora de billetes falsos para comercio y pagos seguros.",
      shortDescription: "Compacta, recargable y fácil de usar.",
      price: 249.00,
      currency: "ARS",
      stock: 58,
      sku: "OFIC_TEST_03",
      rating: 4.1,
      images: ["img/Lápiz Detector Billetes Falsos Marcador.webp"],
      tags: ["seguridad", "oficina", "pago"],
      available: true
    },
    {
      id: "prod-1004",
      slug: "llavero-emoji-peluche",
      name: "Llavero Emoji Peluche",
      category_id: "cat-003",
      description: "Llaveros suaves con caritas emoji para regalar o decorar mochilas.",
      shortDescription: "Disponible en varios modelos y colores.",
      price: 169.00,
      currency: "ARS",
      stock: 120,
      sku: "JUGU_emoji_04",
      rating: 4.3,
      images: ["img/Llavero Grande Whatsapp Emoticones Emoji Peluche de 9cm x 10,5cm.webp"],
      tags: ["regalos", "accesorio", "peluche"],
      available: true
    },
    {
      id: "prod-1005",
      slug: "cargador-usb-rapido-only",
      name: "Cargador Rápido Only",
      category_id: "cat-001",
      description: "Cargador USB de pared con puerto rápido para móviles y tablets.",
      shortDescription: "Incluye cable y protege contra sobrevoltaje.",
      price: 439.00,
      currency: "ARS",
      stock: 72,
      sku: "ELECT_CHRG_05",
      rating: 4.5,
      images: ["img/Cargador Cabezal Only Yexa Mini 4A 1 Usb Hembra + Cable Usb A Tipo C.webp"],
      tags: ["usb", "carga", "movil"],
      available: true
    },
    {
      id: "prod-1006",
      slug: "cable-lightning-usb-apple",
      name: "Cable Lightning a USB",
      category_id: "cat-001",
      description: "Cable de carga y datos compatible con dispositivos Apple.",
      shortDescription: "Longitud 1 m y conector resistente.",
      price: 299.00,
      currency: "ARS",
      stock: 101,
      sku: "ELECT_USB_06",
      rating: 4.6,
      images: ["img/Cable Premium Serial Metro Usb A Iphone Lightning Con Logo.webp"],
      tags: ["cable", "apple", "datos"],
      available: true
    },
    {
      id: "prod-1007",
      slug: "bolso-viaje-corona",
      name: "Vaso Corona Cerveza",
      category_id: "cat-002",
      description: "Vaso temático con diseño Corona para bebidas frías.",
      shortDescription: "Calidad plástica para uso recreativo.",
      price: 179.00,
      currency: "ARS",
      stock: 48,
      sku: "HOGAR_VASO_07",
      rating: 4.0,
      images: ["img/Vaso Plástico Reforzado 12cm X 7cm Con Diseños – CORON..webp"],
      tags: ["hogar", "fiesta", "decoracion"],
      available: true
    },
    {
      id: "prod-1008",
      slug: "audifonos-lgg-akg",
      name: "Auriculares LG AKG",
      category_id: "cat-001",
      description: "Manos libres con micrófono y control de volumen integrado.",
      shortDescription: "Estilo clásico y buena calidad de audio.",
      price: 529.00,
      currency: "ARS",
      stock: 39,
      sku: "ELECT_AKG_08",
      rating: 4.2,
      images: ["img/Auriculares Lg Akg Con mic. Cable Plug 3.5mm (En Caja).webp"],
      tags: ["audio", "handsfree", "movil"],
      available: true
    },
    {
      id: "prod-1009",
      slug: "cargador-ultra-rapido-tame",
      name: "Cargador Ultra Rápido 3C",
      category_id: "cat-001",
      description: "Cargador con salida 2.1A y cable micro USB incluido.",
      shortDescription: "Ideal para teléfonos y tablets de carga rápida.",
      price: 489.00,
      currency: "ARS",
      stock: 27,
      sku: "ELECT_CHRG_09",
      rating: 4.4,
      images: ["img/Cargador Time Cabezal 2.1 A + Cable Separado Micro Usb V8.webp"],
      tags: ["rapido", "usb", "micro usb"],
      available: true
    },
    {
      id: "prod-1010",
      slug: "lampara-keychain-cob",
      name: "Luz Llave COB Rechargeable",
      category_id: "cat-002",
      description: "Mini luz LED recargable con gancho para llavero y clip multiuso.",
      shortDescription: "Práctica para uso diario y trabajo nocturno.",
      price: 329.00,
      currency: "ARS",
      stock: 64,
      sku: "HOGAR_LUZ_10",
      rating: 4.3,
      images: ["img/Linterna Potente Recargable Imán sos Soporte Llavero Destapador 4X6CM.webp"],
      tags: ["luz", "multifuncion", "llavero"],
      available: true
    }
  ]
};
